language: generic
dist: bionic

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive


# Dependency of the minted package
before_install:
  - sudo apt-get install python-pygments

install:
  - source ./texlive/texlive_install.sh
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check

# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR

script:
  # texliveonfly will download packages automatically, running pdflatex by default. Change compiler with e.g. --compiler=lualatex
  - texliveonfly --arguments="--shell-escape" ./main.tex
  # Compile twice to fix possible references
  - texliveonfly --arguments="--shell-escape" ./main.tex

script: 
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links
  # Build booklets
  - sudo apt-get install coreutils pandoc poppler-utils fragmaster texlive-fonts-recommended bookletimposer
  - cd scripts
  - ./maak_boek_voorpaginas
  - ./maak_boek_1
  - ./maak_boek_2
  - ./maak_boek_3
  - ./maak_boek_4
  - ./maak_boek_5
  - ./maak_boek_6
  - ./maak_boek_7
  - ./maak_boek_8
  - ./maak_boek_minim

after_failure:
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

after_success:
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

